# name: Running the Tests
# on: push
# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Get The Code
#         uses: actions/checkout@v6
#       - name: install NodeJs
#         uses: actions/setup-node@v6
#         with:
#           node-version: 24
#       - name: Install dependencies
#         run: npm ci
#       - name: Run Tests
#         run: npm test
